config/routes.rb
Rails.application.routes.draw do
  # get 'trips/new'
  # get 'trips/create'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :trips, only: %i[index new create show] do
    resources :tickets, only: %i[create] 
  end

  resources :broughts, only: %i[index]
  resources :tickets, only: %i[show index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  CLASS_OPTIONS = ['First Class', 'Executive Class', 'Economic Class']

  belongs_to :user
  belongs_to :trip

  validates :user, presence: true
  validates :trip, presence: true

  validates :class_option, inclusion: { in: CLASS_OPTIONS }

  validates_uniqueness_of :user, scope: :trip
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :tickets, dependent: :destroy
  has_many :users, through: :tickets

  validates :origin, :destination, :launch_date, :price, :max_tripulation,
            :spaceship_name, presence: true

  validates :price, numericality: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :trips, dependent: :destroy
  has_many :tickets, dependent: :destroy
  # has_many :tickets, -> { where('users.pilot' => true) }, through: :trips

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :origin_planet,
            presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name origin_planet pilot])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/broughts_controller.rb
class BroughtsController < ApplicationController
  def index
    @tickets = current_user.tickets
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @trip = Trip.new

    search(params)
  end

  private

  # search tickets from user input
  def search(search_params)
    @search_origin = search_params.dig :search, :origin
    @search_destination = search_params.dig :search, :destination
    @search_launch_date = search_params.dig :search, :launch_date

    if search_params[:sent_search] == "true"
      @trips = Trip.all
      @trips = @trips.where(origin: @search_origin) if @search_origin.present?
      @trips = @trips.where(destination: @search_destination) if @search_destination.present?
      @trips = @trips.where(launch_date: @search_launch_date) if @search_launch_date.present?
      @trips = @trips.select { |trip| (trip.max_tripulation - trip.tickets.count).positive? }
    else
      @trips = []
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = current_user.tickets
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def create
    @trip = Trip.find(params[:trip_id])
    # If a pilot tries to buy a ticket from his own TRIP - Return
    return if current_user.pilot && current_user.trips.include?(@trip)

    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    @ticket.trip = @trip

    # Redirect pilots to the right path when they buy a ticket
    if @ticket.save && current_user.pilot
      redirect_to broughts_path(play_song: true)
      return
    end

    # Redirect passengers to the right path when they buy a ticket
    if @ticket.save && !current_user.pilot
      redirect_to trips_path(play_song: true)
    else
      render "trips/show"
    end
  end

  def ticket_params
    params.require(:ticket).permit(:class_option)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[show]
  def index
    @trips = current_user.trips
    @tickets = current_user.tickets
    @spaceship_images = spaceship_images
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def show
    @trip = Trip.find(params[:id])
    @ticket = Ticket.new
  end

  private

  def trip_params
    params.require(:trip).permit(:origin, :destination,
                                 :launch_date, :price, :spaceship_name, :max_tripulation)
  end

  def set_trip
    @trip = Trip.find(params[:id])
  end

  # Get random images to display on views
  def spaceship_images
    [
      "spaceship1", "spaceship2", "spaceship3",
      "spaceship4", "spaceship5", "spaceship6",
      "spaceship7", "spaceship8", "spaceship9"
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/broughts/index.html.erb
<%# List all current_Pilot Tickets %>
<% if user_signed_in? && current_user.pilot %>
    <div class="container d-flex flex-column align-items-center justify-center">
        <% unless current_user.tickets.empty? %>
            <h2>Here are your Tickets, Enjoy the Journey!</h2>
                <% @tickets.each do |ticket| %>
                    <div class="card-product card-product-resize">

                        <div class="spaceship-image">
                            <%# <%= image_tag "spaceship_images/#{@spaceship_images.sample}" %>
                        </div>
                        
                        <div class="card-product-infos p-5 text-color-p">
                            <p><strong>Pilot:</strong> <%= ticket.trip.user.first_name %></p>
                            <p><strong>Origin:</strong> <%= ticket.trip.origin %></p>
                            <p><strong>Destination:</strong> <%= ticket.trip.destination %></p>
                            <p><strong>Paid Price:</strong> <%= "#{ticket.trip.price} Millions" %></p>
                            <p><strong>Spaceship Name:</strong> <%= ticket.trip.spaceship_name %></p>
                            <p><strong>Travel Date:</strong> <%= ticket.trip.launch_date.strftime("%d-%m-%Y") %></p>
                        </div>
                    </div>
                <% end %>
        <% else %>
            <%# Option to Buy Tickets If doesn't have any %>
            <div class="container d-flex flex-column align-items-center justify-center">
                <div  div class="card-product card-product-resize rounded">
                    <%= image_tag "no-tickets-show" %>
                    <div class="card-product-infos p-5 ">
                        <% if current_user.tickets.empty? %>   
                            <h3 class="no-ticket pl-5">You don't have any tickets yet</h3> 
                            <p class="pl-5 mt-5">You can browse and buy tickets clicking the button below:</p>
                            <%= link_to "Get A Ticket Now", root_path, class: "btn btn-primary mt-5 ml-5"  %>
                        <% end %>
                    </div>  
                </div>
        <% end %>
    </div>
<% end %>

<%= audio_tag "starman.mp3", id: "starman" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cosmonaut</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'astronaut-ingravity-white.png' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render './devise/shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="star-small"></div>
    <div class="star-mid"></div>
    <div class="star-large"></div> 
    <div class="my-container w-100">
      <div class="star-small"></div>
      <div class="star-mid"></div>
      <div class="star-large"></div>
      <%= yield %>
      
    </div>
  </body>
</html>

app/views/pages/home.html.erb
  <%# Home will render Welcome to the logged users %>
  <% if user_signed_in? %>
  <div class="container d-flex flex-column align-items-center justify-center">
      <h2 class="mt-5 py-2">
          Welcome! <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>
      </h2>
      <%# Show Pilots an option to create Trips %>
       <% if user_signed_in? && current_user.pilot %> 
          <div class="card-product mb-5 pb-5">
            <%= image_tag "card-background" %>
            <div class="card-product-infos p-5">
              <h2 class="py-3 mt-5"><strong>As a Pilot</strong>, you can create your own trips:</h2>
              <%= link_to 'Create your Trip',  new_trip_path, class: 'btn btn-primary btn-space mt-5'  %>
            </div>
          </div>
      <% end %>
      <%# Trips Search  %>
      <h5 class="pt-3 mt-3">Search for a trip:</h5>
          <%= simple_form_for :search, wrapper: :inline_form, html: { class: 'form-inline  mt-3' }, url: root_path, method: "GET" do |f| %>
            <div class="search-form pr-5">
              <%= f.input :origin, collection: Set.new(Trip.pluck(:origin) + Trip.pluck(:destination)), include_blank: "-- Select Origin --" %>
              <%= f.input :destination, collection: Set.new(Trip.pluck(:origin) + Trip.pluck(:destination)), include_blank: "-- Select Destination --" %>
              <%= f.input :launch_date, collection: Trip.pluck(:launch_date).map { |date| date.strftime("%b %d, %Y") }, include_blank: "-- Select Launch Date --" %>

              <%= hidden_field_tag 'sent_search', 'true'  %>  

              <%= f.submit 'Find a Trip', class: 'btn btn-primary' %>
            </div>
        <% end %>
      <%# Show Search Results (Trips) %>
      <% @trips.each do |trip| %>
        <div class="card-product card-product-resize">  
              <div class="card-product-infos p-5">
                  <p>Origin: <%= trip.origin %></p>
                  <p>Destination: <%= trip.destination %></p>
                  <p>Trip Price: <%= "#{trip.price} Millions" %></p>
                  <p>Spaceship Name: <%= trip.spaceship_name %></p>
                  <p>Max Tripulation: <%= trip.max_tripulation %></p>
                  <p>How many slots available: <%= trip.max_tripulation - trip.tickets.count %></p>
                  <p><%= link_to "Buy Ticket", trip_path(trip) %></p>
                </div>
        </div>
        <% end %>
    </div>
  <% end %>

 
  <%# Public Home Page - Unlogged Users %>
  <% unless user_signed_in? %>
    <div class="container d-flex flex-column align-items-center justify-center glow">
      <h1>Welcome to Cosmonaut <i class="fas fa-space-shuttle header-icon"></i></h1><br>
      <h2>your best friend to travel the universe</h2>
    </div>
  <% end %>

app/views/trips/_form.html.erb
<%# Partial Form to New Trips %>
<%= simple_form_for trip do |f| %>
    <%= f.input :origin, label: 'Origin Planet: ', collection: Set.new(Trip.pluck(:origin) + Trip.pluck(:destination)), include_blank: "-- Select Origin --"%><br>
    <%= f.input :destination, label: 'Destination Planet: ', collection: Set.new(Trip.pluck(:origin) + Trip.pluck(:destination)), include_blank: "-- Select Destination --" %><br>
    <%= f.input :launch_date, label: 'Launch Date: ', as: :date, html5: true %><br>
    <%= f.input :price, label: 'Price *Millions: ', collection: (1..20), include_blank: "-- Select Price In Millions --" %><br>
    <%= f.input :spaceship_name, label: 'Spaceship Name: ', placeholder: "Tell us your Spaceship's name" %><br>
    <%= f.input :max_tripulation, label: 'Max Tripulation: ', collection: (1..10), include_blank: "-- Select how many seats your Spaceship has --" %><br>
    <div class="d-flex justify-content-between">
      <%= f.submit class: 'btn btn-success mt-2 mb-5 mr-5 w-50' %>
      <%= link_to "Back to Home",  root_path, class: 'btn btn-primary mt-2 mb-5'  %>
    </div>
<% end %>

app/views/trips/index.html.erb
<%# If current_Pilot has any Trips - List all Trips  %>
<% if user_signed_in? && current_user.pilot %>
    <div class="container d-flex flex-column align-items-center justify-center">
    <% unless current_user.trips.empty? %>
        <h2>Here are your Trips, Drive Safely!</h2>
            <% @trips.each do |trip| %>
                <div class="card-product card-product-resize">

                    <div class="spaceship-image">
                        <%= image_tag "spaceship_images/#{@spaceship_images.sample}" %>
                    </div>

                    <div class="card-product-infos p-5 text-color-p">
                        <p><strong>Origin:</strong> <%= trip.origin %></p>
                        <p><strong>Destination:</strong> <%= trip.destination %></p>
                        <p><strong>Trip Price:</strong> <%= "#{trip.price} Millions" %></p>
                        <p><strong>Spaceship Name:</strong> <%= trip.spaceship_name %></p>
                        <p><strong>Max Tripulation:</strong> <%= trip.max_tripulation %></p>
                        <p><strong>How many slots available:</strong> <%= trip.max_tripulation - trip.tickets.count %></p>
                        <p><%= link_to "Trip Details", trip_path(trip) %></p>
                    </div>
                </div>
            <% end %>
        <% else %>
            <%# if Pilot has no tickets - Show Options to Buy Tickets and Create a Trip  %>
            <div class="container d-flex flex-column align-items-center justify-center">
                <div  div class="card-product card-product-resize rounded">
                    <%= image_tag "no-tickets-show" %>
                    <div class="card-product-infos">
                        <% if current_user.tickets.empty? %>   
                            <p class="pl-5 ml-5">No Trips Yet</p>
                            <div class="container d-flex flex-row align-items-center justify-center">
                                <%= link_to "Get A Ticket Now!", root_path, class: "btn btn-primary mt-5 ml-5"  %>
                                <%= link_to "Create your Trip Now!", new_trip_path, class: "btn btn-success mt-5 ml-5"  %>
                            </div>
                        <% end %>
                    </div>  
                </div>
        <% end %>
    </div>
<% end %>

<%# if Passenger has any Tickets = List all Tickets %>
      <% else %>
          <div class="container d-flex flex-column align-items-center justify-center">
              <div  div class="card-product card-product-resize rounded">
                  <%= image_tag "no_trips_created" %>
                  <div class="card-product-infos p-5 text-color-p">
                          <h3 class="no-trip pl-5">You haven't created any trips yet</h3> 
                          <p class="above-button pl-5 mt-5">You can browse tickets and create trips clicking the buttons below:</p>
                          <div class="container d-flex flex-row align-items-center justify-center">
                              <%= link_to "Get a Ticket", root_path, class: "btn btn-primary mt-5 ml-5"  %>
                              <%= link_to "Create a Trip", new_trip_path, class: "btn btn-success mt-5 ml-5"  %>
                          </div>
                  </div>  
              </div>
          </div>
      <% end %>
    </div>
<% end %>

<% if user_signed_in? && !current_user.pilot %>
    <div class="container d-flex flex-column align-items-center justify-center">
        <% unless current_user.tickets.empty? %>
            <h2>Here are your Tickets, Enjoy the Journey!</h2>
                <% @tickets.each do |ticket| %>
                    <div class="card-product card-product-resize">

                        <div class="spaceship-image">
                            <%= image_tag "spaceship_images/#{@spaceship_images.sample}" %>
                        </div>
                        
                        <div class="card-product-infos p-5 text-color-p">
                            <p><strong>Pilot:</strong> <%= ticket.trip.user.first_name %></p>
                            <p><strong>Origin:</strong> <%= ticket.trip.origin %></p>
                            <p><strong>Destination:</strong> <%= ticket.trip.destination %></p>
                            <p><strong>Paid Price:</strong> <%= "#{ticket.trip.price} Millions" %></p>
                            <p><strong>Spaceship Name:</strong> <%= ticket.trip.spaceship_name %></p>
                            <p><strong>Travel Date:</strong> <%= ticket.trip.launch_date.strftime("%d-%m-%Y") %></p>
                        </div>
                    </div>
                <% end %>
        <% else %>
            <%# Show Passengers an option to buy tickets if he hasn't any tickets. %>
            <div class="container d-flex flex-column align-items-center justify-center">
                <div  div class="card-product card-product-resize rounded">
                    <%= image_tag "no-tickets-show" %>
                    <div class="card-product-infos p-5 ">
                        <% if current_user.tickets.empty? %>  
                            <h3 class="no-ticket pl-5">You don't have any tickets yet</h3> 
                            <p class="pl-5 mt-5">You can browse and buy tickets clicking the button below:</p>
                            <%= link_to "Get A Ticket Now", root_path, class: "btn btn-primary mt-4 ml-5"  %>
                        <% end %>
                    </div>  
                </div>
        <% end %>
    </div>
<% end %>
<%# Audio played when a ticket is bought  %>
<%= audio_tag "starman.mp3", id: "starman" %>

app/views/trips/new.html.erb
<%# Page New for Trip - Render Partial Form %>
<div class="container d-flex flex-column align-items-center justify-center">
    <h2 class="trip-title">Create your own Trip</h2>
    <div class="container w-50">
        <%= render 'form', trip: @trip %>
    </div>
</div>

app/views/trips/show.html.erb
 
    <%# List all Passengers of the current_Pilot's Trip  %>
    <% if user_signed_in? && current_user.pilot && current_user.trips.include?(@trip)  %>
        <div class="container d-flex flex-column align-items-center justify-center">
             <div  div class="card-product card-product-resize">
                <%= image_tag "card-background-option-2" %>
                <div class="card-product-infos p-5">
            
                    <% if @trip.tickets.empty? && current_user.trips.include?(@trip) %>   
                        <p>No Passengers Yet</p>
                    <% else %>
                        <p><strong>Travel Date:</strong> <%= @trip.launch_date.strftime("%d-%m-%Y") %></p>
                        <p><strong>Passengers: </strong></p>
                        <ul>
                            <% @trip.tickets.each do |ticket| %>
                            <li><p><%= ticket.user.first_name %> <%= ticket.user.last_name %></p></li>
                            <% end %>
                        </ul> 
                    <% end %>
                </div>  
        </div>
    <% end %>

    <%# All Users Can Buy a Ticket but Pilots can't buy tickets of their own Trips %>
    <% if user_signed_in? %>
        <% unless current_user.pilot && current_user.trips.include?(@trip) %>
            <div class="container d-flex flex-column align-items-center justify-center">
                <h2 class="title-ticket">Your Trip Info:</h2>

                <div class="card-product card-product-resize" id="class-selection-card">
                    <div class="card-img-astro">
                        <%= image_tag "card-background-option-2" %>
                    </div>
                    
                    <div data-controller="success" class="card-product-infos pt-3 pr-3 pl-3 pb-0 text-color-p" >
                        <p><strong>Origin:</strong> <%= @trip.origin %></p>
                        <p><strong>Destination:</strong> <%= @trip.destination %></p>
                        <p><strong>Price:</strong> <%= "#{@trip.price} Millions" %></p>
                        <p><strong>Spaceship Name:</strong> <%= @trip.spaceship_name %></p>
                        <p><strong>Max Tripulation:</strong> <%= @trip.max_tripulation %></p>

                        <div id="info-end">
                            <p><strong>Available Seats:</strong> <%= @trip.max_tripulation - @trip.tickets.count %></p>
                        </div>
                    
                        <%= simple_form_for [@trip, @ticket] do |f| %>
                            <%= f.error :user %>
                            <div class="d-flex align-items-center">
                                <%= f.input :class_option,
                                            include_blank: false,
                                            label: false,
                                            collection: Ticket::CLASS_OPTIONS,
                                            wrapper_html: { class: 'mb-0 pr-4',  data: {"success-target": "hidden"} }            
                                %>
                                <div>
                                    <%= f.submit "Buy Ticket", class: "btn btn-success", id: "buy-button" %>
                                </div>
                            </div>
                        <% end %>                      
                </div>
            </div> 
        <% end %>     
    <% end %>
    